### ISSUE TITLE
Some Indian languages Inscript keyboard layouts do not conform to the Standard. 

### ISSUE THREAD

**Issue by nitin-53** [ibus/ibus-m17n#30]
I usually type in Hindi and Punjabi using _ibus-m17n_. Today I found that the **Inscript layouts** available in _ibus-m17n_ are not in accordance with the **standard published by the Government of India** for Indian languages. Most of the keyboard mappings are correct but some of the characters are wrongly associated.

This problem creates confusion when we use different systems viz Mac or Windows. I have not gone through all the Inscript language layouts available in _ibus-m17n_ but there are some wrong keyboard mappings in other Inscript language layouts also. But I think it is very important and urgent to fix these layouts to make them conform with the Standard provided by the Government of India.

The standard can be found on the **BIS (Bureau of Indian Standards)** website. The standard number is [**IS 16350:2016**](https://standardsbis.bsbedge.com/BIS_searchstandard.aspx?Standard_Number=IS+16350&id=22277) titled as **Enhanced Inscript Keyboard Layouts**. I'm also attaching the [link](https://github.com/nitin-53/Enhanced_Inscript_Keyboard_Layout) of _Enhanced Inscript Keyboard Layouts_ images in a zip folder. These layouts were developed by [**C-DAC**](https://cdac.in/index.aspx?id=mc_s_inscript) and available on the [website](http://ildc.in/Inscript-layout.html) to download.

**Comment by pnemade** [comment]
Do you have specific issues to point to start with what you want to report here? At least tell us here few examples of which keymap, which keymappings are not as per standard.

**Comment by nitin-53** [comment]
I'm attaching two images containing both _m17n_ layouts (at the top) and _standard_ layout (at the bottom) of Hindi (Devanagari Script) and Punjabi (Gurumukhi Script). The rectangles in _red_ colour in _m17n_ Inscript layouts show the difference in key mapping in m17n and the standard layout for corresponding keys.

**Hindi**
![m17n_inscript_hindi_layout_vs_ standard_inscript_hindi_layout](https://user-images.githubusercontent.com/18228483/117574579-70c26500-b0fb-11eb-8a3f-cf696e248105.png)

**Punjabi**
![m17n_inscript_punjabi_layout_vs_standard_inscript_punjabi_layout](https://user-images.githubusercontent.com/18228483/117574582-7324bf00-b0fb-11eb-9a38-84a7b314a927.png)

**Comment by mike-fabian** [comment]
By the way, did you know that you can use all m17n input methods not only with ibus-m17n but also with ibus-typing-booster?
ibus-typing-booster has some extra features like completing words from dictionaries and from words you already typed before.

**Comment by nitin-53** [comment]
@mike-fabian Sir, but standardization is also important. Because if there is no uniformity across different OS, then this will create a problem for a typist. I could also ignore it because mostly I use Linux. I recommended Linux to one of my friends and he was using this _ibus-m17n_ method to practice for a typing test to get a job.
If he continued to learn typing on Linux then he would probably unsuccessful in his typing test, because 'Standard' layout is to be used in the test. So updating the keyboard layouts are quite necessary in my opinion to avoid any confusion and also it will keep the input system up to date.

Thank you.

**Comment by mike-fabian** [comment]
Yes, of course, the layouts need to be fixed to agree with the standard, no question about that. 

If the layouts are wrong, they are in ibus-m17n **and** in ibus-typing-booster and this definitely needs to be fixed.

**Comment by nitin-53** [comment]
Thank you so much @mike-fabian Sir to understand my concern. I know it is a long work and it will take substantial time and efforts. I will be available for any help that I can do.
Thank You Sir.

**Comment by pnemade** [comment]
I just had a look at this issue and found out that the issue reported here is showing old inscript keymap image. We already have inscript2 keymaps in Fedora. @nitin-53 Please check inscript2 keymaps and tell us if you have any issues using them.

**Comment by mike-fabian** [comment]
@nitin-53 Are you using Fedora?

**Comment by nitin-53** [comment]
@mike-fabian No Sir, I'm not using Fedora.

**Comment by nitin-53** [comment]
@pnemade Sir, I have cloned that repository (inscript2) and I have already installed that on my system. I'm testing all new layouts. These layouts seem to agree with Standard. I will update you after finishing testing.

Thank you Sir.

**Comment by nitin-53** [comment]
This keyboard layout problem has been solved now with the help of @pnemade  sir. I found 1 more issue in selecting the input method in ibus preferences. There is no option to select input method for Bodo/Boro and Manipuri languages. And there is no option to select Santali Ol Chiki script layout.
May I know whether inscript2 will be available as a package on other distros also in future.
Thank you.

**Comment by pnemade** [comment]
You need to check "Other" to select all those input methods. 
I have not finished my review yet. Once its done. I will make a new tarball release. 
Then we can update Fedora.
I will update here.

**Comment by nitin-53** [comment]
@pnemade Sir Bodo/Boro inscript2 is available in _Others_. But Manipuri ans Santali Ol Chiki is not available. I also used _ibus list-engine_ command but did not find it.

**Comment by mike-fabian** [comment]
> @pnemade Sir Bodo/Boro inscript2 is available in _Others_. But Manipuri ans Santali Ol Chiki is not available. I also used _ibus list-engine_ command but did not find it.

To make Manipuri and Santali Ol Chiki available you need to apply this patch from the Fedora package:

https://src.fedoraproject.org/rpms/m17n-db/blob/rawhide/f/m17n-db-1.8.0-inscript2-mni-sat.patch

**Comment by nitin-53** [comment]
> To make Manipuri and Santali Ol Chiki available you need to apply this patch from the Fedora package:
> 
> https://src.fedoraproject.org/rpms/m17n-db/blob/rawhide/f/m17n-db-1.8.0-inscript2-mni-sat.patch

@mike-fabian Sir,  I tried these 4 changes but nothing happened.

**Comment by mike-fabian** [comment]
Did you install the files correctly, i.e. do you have the corrected files in /usr/share/m17n/mni-inscript2-mtei.mim etc..?

If yes, you should be able to list them with  `ibus-engine-m17n --xml` like this:

```
$ /usr/libexec/ibus-engine-m17n --xml 2>/dev/null | grep '<name>.*inscript2'
            <name>m17n:mr:inscript2</name>
            <name>m17n:ne:inscript2</name>
            <name>m17n:ta:inscript2</name>
            <name>m17n:te:inscript2</name>
            <name>m17n:sa:inscript2</name>
            <name>m17n:kok:inscript2</name>
            <name>m17n:bn:inscript2</name>
            <name>m17n:kn:inscript2</name>
            <name>m17n:hi:inscript2</name>
            <name>m17n:mni:inscript2-beng</name>
            <name>m17n:mni:inscript2-mtei</name>
            <name>m17n:mai:inscript2</name>
            <name>m17n:gu:inscript2</name>
            <name>m17n:as:inscript2</name>
            <name>m17n:or:inscript2</name>
            <name>m17n:pa:inscript2</name>
            <name>m17n:sat:inscript2-deva</name>
            <name>m17n:sat:inscript2-olck</name>
            <name>m17n:sd:inscript2</name>
            <name>m17n:ml:inscript2</name>
            <name>m17n:doi:inscript2</name>
            <name>m17n:brx:inscript2</name>
$ 
```

and with `ibus list-engine`:

```
$ ibus list-engine | grep inscript2-olck
  m17n:sat:inscript2-olck - inscript2-olck (m17n)
$ ibus list-engine | grep inscript2-mtei
  m17n:mni:inscript2-mtei - inscript2-mtei (m17n)
$
```

**Comment by pnemade** [comment]
if some keymaps are getting renamed due to conflicts like shown above then I am going to rename other keymaps also. e.g. those having name ending -deva to also include -deva in keymap name. This will then match similar naming for all keymaps having script name in their filename.

**Comment by pnemade** [comment]
Yes I too observed the same. mni-inscript2-mtei is not in that list. Will check more on it later.

**Comment by mike-fabian** [comment]
> Yes I too observed the same. mni-inscript2-mtei is not in that list. Will check more on it later.

Maybe you have the version recently from Fedora when the patches were not applied?

**Comment by mike-fabian** [comment]
Note that after editing `/usr/share/m17n/mni-inscript2-mtei.mim` (or applying the patch), you need to do `ibus restart` (when not using Gnome) or restart your Gnome session when using Gnome. Otherwise you don’t see any change in `ibus list-engine`.

**Comment by mike-fabian** [comment]
I am closing this because it is not an ibus-m17n bug but rather a bug in m17n-db and Parag Nemade is dealing with it there. I think he already fixed it.
