### ISSUE TITLE
Icons for each layout.

### ISSUE THREAD

**Issue by jakubfabijan** [ibus/ibus-m17n#31]
Is there a way to set an icon for every m17n layout instead of ![bildo](https://user-images.githubusercontent.com/53099243/124346828-54b1e000-dbe1-11eb-9a7d-a0b24e0ef455.png)?

**Comment by jakubfabijan** [comment]
Is there any way to do it?

**Comment by pnemade** [comment]
if you have your keymap .mim file in /usr/share/m17n then install the similar named icon file in .png format.
e.g. /usr/share/m17n/hi-inscript.mim keymap used /usr/share/m17n/icons/hi-inscript.png

Can you tell us here which keymap you are using that have no icon installed? I know not all keymaps have corresponding icon files.

**Comment by jakubfabijan** [comment]
Thanks for answer. I made my own keymap: Dvorak for Esperanto. I was using it a lot of time as xkb but now when I am using multiple languages I prefer ibus.

**Comment by mike-fabian** [comment]
Were you successful in adding your icon?

**Comment by jakubfabijan** [comment]
Actually not, I did put an icon file (.png) in that path, with the same as layout name but nothing changed, tried multiple times with 2 different png files. I just gave up because it's not that important to me :P

**Comment by mike-fabian** [comment]
Weird, because that should work (and works for me).

You can also create an ~/.m17n.d/ folder in your home directory and use that one like:

```
$ find ~/.m17n.d/ -name "ipa*"
/home/mfabian/.m17n.d/ipa-x-sampa.mim
/home/mfabian/.m17n.d/icons/ipa-x-sampa.png
```

But the system folder works as well.

Is your .png file OK?

```
$ file ~/.m17n.d/icons/ipa-x-sampa.png 
/home/mfabian/.m17n.d/icons/ipa-x-sampa.png: PNG image data, 48 x 48, 16-bit/color RGB, non-in
terlaced
```

**Comment by mike-fabian** [comment]
> Is there a way to set an icon for every m17n layout instead of ![bildo](https://user-images.githubusercontent.com/53099243/124346828-54b1e000-dbe1-11eb-9a7d-a0b24e0ef455.png)?

Where exactly do you see this icon? Which desktop? Which distribution?

**Comment by jakubfabijan** [comment]
I even tried with different layout that I also made. Doesn't work too. 
![bildo](https://user-images.githubusercontent.com/53099243/126539127-950033c1-7f43-4a21-bb92-6de200f31f81.png)
`~/.m17n.d`

![bildo](https://user-images.githubusercontent.com/53099243/126539239-caa78e2b-253b-4e11-94d2-9329b6d67215.png)
`~/.m17n.d/icons` (2 files because I wanted to make sure it will work)

![bildo](https://user-images.githubusercontent.com/53099243/126539474-b5bdb435-d3ed-4d4a-b77a-e59cf1c252ab.png)
I see this icon in the tray when you can simply change layout, it should show icon of current layout, for example here you see "PL" icon for polish layout. But for my layout's it shows "I" icons instead of my icons.

System: Arch Linux; Bar: tint2; WM: Fluxbox;

**Comment by mike-fabian** [comment]
it works for me on Fedora 34 with fluxbox with my own ipa-x-sampa input method:

( https://github.com/mike-fabian/m17n-db-ipa-x-sampa )

[mfabian@fedora ~]$ find .m17n.d/ -iname "*ipa*"
.m17n.d/ipa-x-sampa.mim
.m17n.d/icons/ipa-x-sampa.png
[mfabian@fedora ~]$ 

![Screenshot](https://user-images.githubusercontent.com/2330175/126620004-befcabce-08d5-4c9e-8fb3-ad3584ba5d11.png)

**Comment by jakubfabijan** [comment]
I will just leave it. I have no idea how to make it work, and I don't really have time to try every single way. I just hope it's a problem with my OS not with the program itself, so only I am experiencing it. Anyway, thanks for help.

**Comment by mike-fabian** [comment]
Fluxbox with tint2 on Fedora 34, works as well:

![Screenshot](https://user-images.githubusercontent.com/2330175/126626163-5682a573-563e-44f9-9070-9ca2060fdb2b.png)

**Comment by mike-fabian** [comment]
Could you attach your icon here?

**Comment by jakubfabijan** [comment]
[Here](https://a.tmp.ninja/jRNhPMb.png)

**Comment by mike-fabian** [comment]
That icon works correctly for me in my i3 session.

**Comment by mike-fabian** [comment]
So I think the icon is OK.

**Comment by mike-fabian** [comment]
Could you also share your .mim file? Maybe there  is a mistake in the .mim file which causes that the icon is not found.

**Comment by jakubfabijan** [comment]
Sorry for long time of inactivity. This is the content of my layout file tokipona.mim:

`(input-method tp linjapona)

(title "toki pona")

(description (_"Meant for writing toki pona."))

(map
  (trans
 
("r" "ᑕ")
("t" "ᑐ")
("y" "ᑌ")
("i" "○")
("o" "•")
("d" "△")
("f" "＜")
("g" "＞")
("h" "ᐯ")
("j" "ᐱ")
("k" "／")
("l" "＼")
("x" "▢")
("c" "⊏")
("v" "⊐")
("b" "⊔")
("n" "⊓")
("m" "|")
("," "—")
("mil" "")
("e,,,oo" "")
("kl" "")
("lk" "")
("tm,g" "")
("mt,g" "")
("ee" "")
("bo" "")
("ob" "")
("hj" "")
("jh" "")
("mh" "")
("hm" "")
(",j," "")
("j,," "")
(",,j" "")
("gg" "")
("m," "")
(",m" "")
("tkr" "")
("tmr" "")
("e" "" )
("u" "")
("xm" "")
("mx" "")
("bo" "")
("ob" "")
("ttru" "")
("urtt" "")
("urtrt" "")
("urtrt" "")
("ekl" "")
("kle" "")
("kel" "")
("lek" "")
("di,,m" "")
("i,,m" "")
("im,," "")
("dim,," "")
("im,,d" "")
("di,m," "")
("i,m,d" "")
("ir," "")
(",ri" "")
("ri," "")
("yu" "")
("uy" "")
("y,lkm" "")
(",ylkm" "")
("lkm,y" "")
("lkmy," "")
("lj," "")
(",kl," "")
(",lk," "")
("lk,," "")
("kl,," "")
(",,lk" "")
   ))

(state
  (init
    (trans)))
`

**Comment by mike-fabian** [comment]
I think you should do the following changes to your tokipona.mim file, then the icon will work:

```
$ diff tokipona.mim.orig tokipona.mim
1c1
< (input-method tp linjapona)
---
> (input-method t tokipona)
5c5
< (description (_"Meant for writing toki pona."))
---
> (description "Meant for writing toki pona.")
```

Because of `(input-method tp linjapona)` it was actually searching for an icon file named tp-linjapona.png which did not exist.

With `(input-method t tokipona)` it now searches for an icon file named t-tokipona.png and if that still doesn’t exist it searches for tokipona.png.

I think the first argument `input-method` should not be `tp` but `t` because in that place one should put the ISO 639-1 or ISO 639-3 language code. But toki pona has no such code assigned yet.

`t` in that place is special and means “It is an input method for something else, something where we cannot specify a ISO language code, either because no one has been specified or because this is an input method which supports several different languages at the same time or maybe because it is a input method for mathematical symbols or ...”.

So always use `t` there if specifying one single ISO language code makes no sense.

After `description`, there should be only a string, i.e. just `"Meant for writing toki pona."`, not `(_"Meant for writing toki pona.")`

**Comment by mike-fabian** [comment]
I suggest to name the files

```
tokipona.mim
icons/tokipona.png
```

(`t-tokipona.mim` and `icons/t-tokipona.png` would also work, but it seems to be the custom in m17n-db to omit the `t-` in the file names:

When an ISO code exists, like in this example for Hindi the ISO 639-1 code is `hi`, this is used as the prefix in the file names:

```
$ grep '(input-method' /usr/share/m17n/hi-itrans.mim
(input-method hi itrans)
$ ls /usr/share/m17n/hi-itrans.mim /usr/share/m17n/icons/hi-itrans.png -1
/usr/share/m17n/hi-itrans.mim
/usr/share/m17n/icons/hi-itrans.png
$
```

But for input methods which use the special `t` code it is usually omitted in the file names:

```
$ grep '(input-method' /usr/share/m17n/latn-post.mim 
(input-method t latn-post)
$ ls /usr/share/m17n/latn-post.mim /usr/share/m17n/icons/latn-post.png -1
/usr/share/m17n/icons/latn-post.png
/usr/share/m17n/latn-post.mim
$
```

**Comment by mike-fabian** [comment]
Here is the exact pair of `tokipona.mim` and `icons/tokipona.png` files I used for testing:

[tokipona.zip](https://github.com/ibus/ibus-m17n/files/6959961/tokipona.zip)

Using these, the icon works. (Don’t forget “ibus restart” after changing the files or restart your session when using Gnome)

**Comment by mike-fabian** [comment]
As it works after the changes to the files I described above, I am closing this.
