### ISSUE TITLE
Allow to use kbd engines

### ISSUE THREAD

**Issue by wladmis** [ibus/ibus-m17n#32]
Despite of similar functionality, m17n kbd engines behave in the different way to xkb engines. For my specific use-case, the m17n kbd engines map Latin key to Cyrillic key only in the text fields while the command hotkeys are handled as Latin. It is very handy when you use smth like Firefox with Tridactyl (the Vimperator remake).

**Comment by mike-fabian** [comment]
See also:

https://github.com/ibus/ibus-m17n/issues/25

**Comment by mike-fabian** [comment]
Apparently you are not using Gnome, Gnome seems to have a hack which makes hotkeys like “Control+a” work **even** **if** the key where the “a” is on the US English keyboard layout produces something else (It produces ф on the Russian keyboard layout).

In this video I use a Gnome desktop and type type into gedit. First I use the US English layout and type:

```
a Control+a Right
```

The Control+a selects all the text in gedit (blue background), the Right (arrow-right) cancels the selection.

Then I switch to the Russian keyboard layout and type the same sequence of keys. Now  the “a”-key produces ф, so actually I type:

```
ф Control+ф Right
```

and the Control+ф selects all text in gedit.

I think Gnome has a hack that if something like Control+ф does nothing, it checks what letter would have been produced when typing the same key on an US layout, which would be an “a” and then tries Control+a.

https://user-images.githubusercontent.com/2330175/128837904-601e582a-08dd-4a4c-a552-b4c4dc419ca3.mp4

**Comment by mike-fabian** [comment]
(All?) other desktops don’t have this hack, so if I try this on my usual i3 desktop, Control+ф does **not** select all text in gedit.

**Comment by mike-fabian** [comment]
You are right that using /usr/share/m17n/ru-kbd.mim via ibus-m17n can be used as a workaround for this, it gives you a Russian keyboard layout (emulated on an US English layout) and the hotkeys still  work.

**Comment by mike-fabian** [comment]
Personally I have nothing against dropping the blacklisting of all the `m17n:*:kbd` engines.

I just counted 30 keyboard layouts/input-methods for Russian offered in the gnome-control-center settings, I don’t really see the harm in making that 31 ...

**Comment by mike-fabian** [comment]
By the way, you can also use the /usr/share/m17n/ru-kbd.mim in ibus-typing-booster.

ibus-typing-booster supports all the input methods from m17n-db and doesn’t blacklist any.

ibus-typing-booster does much more than ibus-m17n, it offers to complete words does lots of others stuff.
But all that extra stuff can be disabled in the options, when the extras are  disabled, ibus-typing-booster behaves just like ibus-m17n (but doesn’t blacklist any m17n-db input methods!):

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#simulate-ibus-m17n

**Comment by wladmis** [comment]
On Tue, Aug 10, 2021 at 02:44:38AM -0700, Mike FABIAN wrote:
> By the way, you can also use the /usr/share/m17n/ru-kbd.mim in ibus-typing-booster.
> 
> ibus-typing-booster supports all the input methods from m17n-db and doesn’t blacklist any.
> 
> ibus-typing-booster does much more than ibus-m17n, it offers to
> complete words does lots of others stuff.
> But all that extra stuff can be disabled in the options, when the
> extras are  disabled, ibus-typing-booster behaves just like ibus-m17n
> (but doesn’t blacklist any m17n-db input methods!):
> 
> http://mike-fabian.github.io/ibus-typing-booster/documentation.html#simulate-ibus-m17n

ibus-typing-booster looks interesting, but even if all the features of
it are disabled, this is too much for me: I just want to select one of
the layout I use, to do some typing and quickly switch back to English
layout.

Anyway I don't see why any engine that is seems redundant should be
blacklisted. While default.xml looks like a policy, an user has no way
to change it, even then he or she still can create $HOME/.m17n.d/, copy
ru-kbd.mim and uk-kbd.mim to that dir, and rename the engine names, and
those engines will work. May be it would be better if every redundant
engines will be set on the lowest priority instead? Just a proposition.

> Closed #32 via 256b8e18112f2c8f43e4c013b082f58b208c6fc5.

Thank you!

**Comment by mike-fabian** [comment]
> Anyway I don't see why any engine that is seems redundant should be blacklisted.

I agree.

> May be it would be better if every redundant engines will be set on the lowest priority instead? Just a proposition.

ibus-setup sorts according to the priority, but the gnome-control-center apparently does not.

**Comment by wladmis** [comment]
> Apparently you are not using Gnome, Gnome seems to have a hack which makes hotkeys like “Control+a” work **even** **if** the key where the “a” is on the US English keyboard layout produces something else (It produces ф on the Russian keyboard layout).
> 
> In this video I use a Gnome desktop and type type into gedit. First I use the US English layout and type:
> 
> ```
> a Control+a Right
> ```
> 
> The Control+a selects all the text in gedit (blue background), the Right (arrow-right) cancels the selection.
> 
> Then I switch to the Russian keyboard layout and type the same sequence of keys. Now the “a”-key produces ф, so actually I type:
> 
> ```
> ф Control+ф Right
> ```
> 
> and the Control+ф selects all text in gedit.
> 
> I think Gnome has a hack that if something like Control+ф does nothing, it checks what letter would have been produced when typing the same key on an US layout, which would be an “a” and then tries Control+a.
> Peek.2021-08-10.10-49.mp4

No, AFAIK Control-ф works just as it is expected everywhere: like Control-a, there is no problem. The problem was when you typed just plane 'ф' symbol somewhere outside text input area and expected it works with effect like you pressed 'a', but nothing happened.

**Comment by wladmis** [comment]
> If you type outside a text input area, ibus-m17n doesn’t get focus and does nothing. That means if you are using ibus-m17n to simulate a Russian keyboard by transliteratig “a” to “ф” then you still get an “a” when you type outside a text input area because ibus-m17n can do nothing there.
> 
> But when you use a “real” Russian keyboard layout, you always get a “ф” when typing that key, no matter whether you do that in a text input area or elsewhere. So you cannot type an “a” (easily) anymore with the “real” Russian keyboard layout.

Thank you for the explanation, it was just as I thought! The interesting thing is that I don't see why would somebody need a "real" Russian keyboard layout: it seems that it requires some external _workarounds_ in to make things work.
