### ISSUE TITLE
Some ibus-m17n engines show wrong symbols in the Gnome panel

### ISSUE THREAD

**Issue by mike-fabian** [ibus/ibus-m17n#34]
Noticed by Parag Nemade,

![Indic-keymap-letters](https://user-images.githubusercontent.com/2330175/129033146-2519c44c-9f87-4354-b2ed-c23d82e241dd.png)

**Comment by mike-fabian** [comment]
After my improvement:

![Screenshot](https://user-images.githubusercontent.com/2330175/129406340-300d1ec6-9951-40e3-bd59-0f6411d46109.png)

**Comment by mike-fabian** [comment]
Note that I couldn’t find a font for the Mtei script on Fedora 34!

I installed an old one from Fedora 29:
```
$ rpm -q tabish-eeyek-fonts.noarch
tabish-eeyek-fonts-1.0-13.fc29.noarch
```

**Comment by mike-fabian** [comment]
I changed the order of the input methods so you can see those which were not visible in the previous screenshot because the menu is cut off at the bottom of the screen:

![Screenshot](https://user-images.githubusercontent.com/2330175/129406825-e3cc5103-85e8-484a-b132-a7b6cd201cda.png)

**Comment by pnemade** [comment]
:+1: 
Very nice work @mike-fabian
