### ISSUE TITLE
Request to accept virtual engine names for CI

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus-m17n#42]
I wish to call ibus_m17n_engine_get_type_for_name() with virtual engine names for CI likes "m17n:mr:inscript2:ci" to distinguish "m17n:mr:inscript2" and establish the test environment easily together with real engines and test engines.

To reproduce:
Call `ibus_m17n_engine_get_type_for_name("m17n:mr:inscript2:ci")`

Failed to create the IBusEngine.

**Comment by fujiwarat** [comment]
Added ibus-m17n CI to ibus-engine-gui-ci
https://github.com/fujiwarat/ibus-engine-gui-ci/commit/1ed15fadb832de7ce271b9357229344bac74084e

**Comment by mike-fabian** [comment]
https://github.com/ibus/ibus-m17n/releases/tag/1.4.9
