### ISSUE TITLE
When typing in Marathi (inscript), character '  ॅ ' appears incorrect.

### ISSUE THREAD

**Issue by sawaiborkar** [ibus/ibus-m17n#44]
While typing in Marathi (Unicode keymapping), the '  ॅ ' appears incorrectly as shown below -
"अॅक्टिंग"
Here, the first second character (  ॅ ) should appear on top of the first (अ). But instead, it is appearing AFTER the first which is incorrect.

**Comment by shantanuo** [comment]
Use Shift + E (i.e. capital e) If using GaMaBhaNa from...

https://github.com/shantanuo/gamabhana

**Comment by mike-fabian** [comment]
As you reported this against ibus-m17n, I assume you use the `/usr/share/m17n/mr-inscript.mim` input method.

ॲ U+0972 DEVANAGARI LETTER CANDRA A
अ U+0905 DEVANAGARI LETTER A
ॅ U+0945 DEVANAGARI VOWEL SIGN CANDRA E
अॅ U+0905 DEVANAGARI LETTER A followed by U+0945 DEVANAGARI VOWEL SIGN CANDRA E

Checking for these characters in the mr-*.mim files I find:

```
mfabian@taka:/usr/share/m17n
$ grep ॲ mr*inscript*mim
mr-inscript2.mim:  ("!" "ॲ")
mfabian@taka:/usr/share/m17n
$ grep अॅ mr*inscript*mim
mfabian@taka:/usr/share/m17n
$ grep अ mr*inscript*mim
mr-inscript.mim:  ("D" ?अ)
mr-inscript2.mim:  ("D" "अ")
mfabian@taka:/usr/share/m17n
$ grep ॅ mr*inscript*mim 
mr-inscript.mim:  ("@" ?ॅ)
mr-inscript2.mim:  ("@" "ॅ")
mfabian@taka:/usr/share/m17n
$
```

So you can type ॲ by typing `!` when using mr-inscript2.mim.

You can type अ followed by ॅ both with inscript and inscript2 by typing `D@` but apparently that doesn’t render correctly (maybe it depends on the font, I’m notsure, but for me it doesn’t put the ॅ on top of अ).

Inserting a U+200D ZERO WIDTH JOINER between अ and ॅ  seems to make it render correctly in some programs (for example it renders correctly in gedit for me then)

With ZERO WIDTH JOINER: अ‍ॅ

You can type the ZERO WIDTH JOINER with inscript2:

```
$ grep ZW mr*inscript*mim
mr-inscript2.mim:ZWJ            AltGr + 1
mr-inscript2.mim:ZWNJ           AltGr + 2
$ grep "G-[12]" mr*inscript*mim
mr-inscript2.mim:  ((G-1) "‍")
mr-inscript2.mim:  ((G-2) "‌")
mfabian@taka:/usr/share/m17n
$
```

So with inscript2, you can type `D AltGr-1 @` and you get अ‍ॅ

**Comment by mike-fabian** [comment]
If you are using fedora, inscript2 is included in this package:

```
$ rpm -qf /usr/share/m17n/mr-inscript2.mim 
m17n-db-1.8.0-21.fc35.noarch
```

**Comment by mike-fabian** [comment]
If you are not using Fedora, you can get the inscript2 input methods from here:


https://releases.pagure.org/inscript2/
https://releases.pagure.org/inscript2/inscript2-20210820.tar.gz

You can unpack the tarball 

```
$ tar tf inscript2-20210820.tar.gz | grep mr-inscript
inscript2/icons/mr-inscript2.png
inscript2/IM/mr-inscript2.mim
```

and then copy the .mim files to `/usr/share/m17n/` and the icons to `/usr/share/m17n/icons`.

**Comment by mike-fabian** [comment]
We are trying to get the inscript2 input methods included upstream at m17n-db.

**Comment by mike-fabian** [comment]
By the way, did you know that you can use all the m17n-db input methods not only with ibus-m17n but also with ibus-typing-booster?

See:

https://mike-fabian.github.io/ibus-typing-booster/
https://github.com/mike-fabian/ibus-typing-booster

ibus-typing-booster has many additional features over ibus-m17n.

But even if one doesn’t need or want any of the additional features, one could still use ibus-typing-booster instead of ibus-m17n and turn all the extra features off:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_2_1_1

**Comment by sawaiborkar** [comment]
Thanks for the help.
I did not about GaMaBhaNa.
Tell me more about it.
Is is inscript based or phonetic?
What do you mean by 'simple' Marathi keyboard?

*(SACHIN BORKAR)*

**Comment by sawaiborkar** [comment]
Fantastic! I installed the mr-inscript2 input method and now I can type 'ॲ'.
Even with mr-inscript method, your suggestion of using U+0972 combination
gives desired results.
Many thanks.
I am also trying out Typing Booster. But I don't see Marathi spellchecking
specifically mentioned.
Please tell me more about it.
Can I type unicode Devanagari script using Typing Booster? Does it support
the inscript2 keyboard layout?
Also I apologize for late reply. I couldn't find sufficient time due to a
rather busy week.
*(SACHIN BORKAR)*

**Comment by mike-fabian** [comment]
> I am also trying out Typing Booster. But I don't see Marathi spellchecking specifically mentioned. Please tell me more about it.

In the setup tool of ibus-typing-booster, just add the mr-inscript2 input method and the mr_IN dictionary (to be able to add that dictionary, the `mr_IN.dic` file needs to be installed, this file is in the hunspell-mr package on Fedora:

```
$ rpm -qf /usr/share/myspell/mr_IN.dic
hunspell-mr-1.0.0-16.fc35.noarch
```

(In other distributions it might be in `/usr/share/hunspell/mr_IN.dic` and the package name might be different. As long as it is installed, ibus-typing-booster will find it, ibus-typing booster searches for `mr_IN.dic` in several directories).

> Can I type unicode Devanagari script using Typing Booster?

Yes.

> Does it support the inscript2 keyboard layout?

Yes.

Here is a video showing the basic language setup of ibus-typing-booster using Hindi as a example:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_1

But it works the same way for Marathi.

For Marathi you probably want the setup as in the following screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/154974511-0cd03918-0e67-4125-b4ad-3346873e62ea.png)

**Comment by shantanuo** [comment]
Is hunspell-mr package available for debian? I am using Ubuntu and last time I checked, this command did  not work... 
apt install hunspell-mr

Hindi (hi) and Gujarati (gu) packages are working as expected but not marathi (in ubuntu). Typing booster without dictionary package is not as effective as it should be. I am aware that I can copy the .dic and .aff files, but a package will be convenient.  Typing booster is already popular. Please do not advertise it in unrelated threads. 
The original poster noted "Even with mr-inscript method, your suggestion of using U+0972 combination
gives desired results." I did not understand this part. Can you elaborate how to type U+0972  in inscript?

**Comment by pnemade** [comment]
I am not a Ubuntu user but I think Ubuntu uses single source package to build multiple binary dictionary packages. Marathi dictionary is not available in Ubuntu.
Technically It is possible to render अ‍ॅ using mr-inscript.mim input method but its not easy for end users of mr-inscript to use it. Mike has already explained how to type ZWJ character.

**Comment by mike-fabian** [comment]
> Is hunspell-mr package available for debian? I am using Ubuntu and last time I checked, this command did not work... apt install hunspell-mr

> Hindi (hi) and Gujarati (gu) packages are working as expected but not marathi (in ubuntu).

I didn’t know but now I searched and could not find hunspell-mr for Debian/Ubuntu either.

The upstream source for the Fedora hunspell-mr package seems to be

https://anishpatil.fedorapeople.org/mr_in.1.0.0.tar.gz

**Comment by mike-fabian** [comment]
> I am aware that I can copy the .dic and .aff files, but a package will be convenient.

By the way, copying the files into the user home directory into `~/.local/share/ibus-typing-booster/data/` also works for typing booster, it searches for dictionaries like this:


https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/itb_util.py#L3065

**Comment by mike-fabian** [comment]
> Typing booster is already popular. Please do not advertise it in unrelated threads.

I maintain both ibus-typing-booster and ibus-m17n at the moment. But the development of ibus-typing-booster is more active, for ibus-m17n I only do minimal bugfixing.

**Comment by mike-fabian** [comment]
> The original poster noted "Even with mr-inscript method, your suggestion of using U+0972 combination gives desired results." I did not understand this part. Can you elaborate how to type U+0972 in inscript?

I did not understand this part either.

ॲ U+0972 DEVANAGARI LETTER CANDRA A is only in mr-inscript2.mim, not in mr-inscript.mim.

And U+200D ZERO WIDTH JOINER is also missing in mr-inscript.mim and only available in mr-inscript2.mim, so I don’t understand how you can type this with mr-inscript.mim.

**Comment by sawaiborkar** [comment]
>
> so I don’t understand how you can type this with mr-inscript.mim.
>
My bad. I am sorry. it's possible only using regular 'en' keyboard layout
and not the mr-inscript.mim method.
Pressing Ctrl + Shift keys simultaneously if I type character 'u', then a
'u' with an underline appears. Then releasing the Ctrl + Shift keys and
typing in the rest of combination (0972) produces the character 'ॲ'.
*(SACHIN BORKAR)*

**Comment by sawaiborkar** [comment]
>
> Is hunspell-mr package available for debian? I am using Ubuntu and last
> time I checked, this command did not work...
>
Nope. hunspell-mr package is not available for Ubuntu.
But aspell-mr package is available.
Is this useful for Typing-Booster?
*(SACHIN BORKAR)*

**Comment by mike-fabian** [comment]
> so I don’t understand how you can type this with mr-inscript.mim.
> it's possible only using regular 'en' keyboard layout and not the mr-inscript.mim method. Pressing Ctrl + Shift keys simultaneously if I type character 'u', then a 'u' with an underline appears. Then releasing the Ctrl + Shift keys and typing in the rest of combination (0972) produces the character 'ॲ'. *(SACHIN BORKAR)*

Ah, I see! This Ctrl+Shift-u is the Unicode input of ibus, as you say it works with all keyboard layouts like the regular 'en' keyboard layout.

This ibus Ctrl+Shift+u does not work when using m17n input methods like mr-inscript.mim via ibus-m17n or ibus-typing-booster.

But while checking this again, I accidentally discovered that the Unicode input method of m17n (`/usr/share/m17n/unicode.mim`) seems to work while **any** m17n input method is active. It is activated by Ctrl+u (not Ctrl+Shift+u) and it displays `U+` with an underline, then you can also type 0972 and get 'ॲ'. I.e. while using mr-inscript (or any other m17n input method, no matter whether via ibus-m17n or ibus-typing-booster), you can type `Ctrl+u 0 9 7 2` to get 'ॲ'. Surprised me. But nice!

The unicode.mim of m17n has the limitation though that it currently only works for 4 digit Unicode code points, see:

https://github.com/ibus/ibus-m17n/issues/4

But for Devanagari that is enough.

The Ctrl+Shift+u Unicode input of ibus does **not** have this limitation.

I hope I can find time to fix unicode.mim to also allow entering higher code points like 😎 U+1F60E .

**Comment by mike-fabian** [comment]
> Is hunspell-mr package available for debian? I am using Ubuntu and last time I checked, this command did not work...
> Nope. hunspell-mr package is not available for Ubuntu. But aspell-mr package is available. Is this useful for Typing-Booster? *(SACHIN BORKAR)*

aspell-mr can not be used unfortunately. Looking at:

https://packages.debian.org/en/bullseye/all/aspell-mr/filelist

it seems to contain no file containing a list of words in plain text like the hunspell dictionaries do.

```
/usr/lib/aspell/marathi.alias
/usr/lib/aspell/mr.dat
/usr/lib/aspell/mr.multi
/usr/share/aspell/mr.cwl.gz
/usr/share/doc/aspell-mr/changelog.Debian.gz
/usr/share/doc/aspell-mr/copyright
/var/lib/dictionaries-common/aspell/aspell-mr
```

`mr.cwl.gz` seems to be the dictionary, all other files are tiny plain text files containing some encoding, charset, and name information.

But `mr.cwl` is a binary file so it cannot be used in that form by ibus-typing-booster.

**Comment by sawaiborkar** [comment]
>
> But while checking this again, I accidentally discovered that the Unicode
> input method of m17n (/usr/share/m17n/unicode.mim) seems to work while
> *any* m17n input method is active. It is activated by Ctrl+u (not
> Ctrl+Shift+u) and it displays U+ with an underline,
>

Indeed! I did not know this. But it has a great downside. While typing in
Libreoffice Writer with the inscript2 input method (and even with the
inscript and Typing Booster), you lose the capacity of using keyboard
shortcut Ctrl + u to underline text! You are then forced to use the mouse
and click the Underline icon for the underlining effect. This happens even
in web-based applications such as Gmail.
Is there any way to rectify this?

*(SACHIN BORKAR)*

**Comment by mike-fabian** [comment]
> But while checking this again, I accidentally discovered that the Unicode input method of m17n (/usr/share/m17n/unicode.mim) seems to work while *any* m17n input method is active. It is activated by Ctrl+u (not Ctrl+Shift+u) and it displays U+ with an underline,
> Indeed! I did not know this. But it has a great downside. While typing in Libreoffice Writer with the inscript2 input method (and even with the inscript and Typing Booster), you lose the capacity of using keyboard shortcut Ctrl + u to underline text! You are then forced to use the mouse and click the Underline icon for the underlining effect. This happens even in web-based applications such as Gmail. Is there any way to rectify this? *(SACHIN BORKAR)*

I don’t know yet. I’ll try to find out. Until today I didn‘t even know that this Ctrl+u feature in m17n input methods exists. It was probably always like this, I just never noticed.

**Comment by mike-fabian** [comment]
@shantanuo I realized you have a Marathi dictionary which is probably much better than the hunspell-mr dictionary currently in Fedora:

https://github.com/shantanuo/spell_check
https://extensions.libreoffice.org/en/extensions/show/marathi-spellchecker
https://extensions.libreoffice.org/en/extensions/show/1979

To get it  included into Debian/Ubuntu, it might be helpful to get your dictionary listed at 

https://wiki.documentfoundation.org/Development/Dictionaries

because the debian maintainers seem to use that as a reference:

https://salsa.debian.org/libreoffice-team/libreoffice/libreoffice-dictionaries/-/blob/master/dictionaries/README

Maybe also ping the debian maintainers to include it. 

For Fedora it would  also be nice if we could update our hunspell-mr package to use your improved version.

There seems to be a problem with the version numbering though, it make it easier for distribution package maintainers if you could make a new release with a consistent version numbering. Even if your dictionary stays exactly the same, a new release with consistent version numbering would be worth doing in my opinion.

**Comment by mike-fabian** [comment]
> But while checking this again, I accidentally discovered that the Unicode input method of m17n (/usr/share/m17n/unicode.mim) seems to work while *any* m17n input method is active. It is activated by Ctrl+u (not Ctrl+Shift+u) and it displays U+ with an underline,
> Indeed! I did not know this. But it has a great downside. While typing in Libreoffice Writer with the inscript2 input method (and even with the inscript and Typing Booster), you lose the capacity of using keyboard shortcut Ctrl + u to underline text! You are then forced to use the mouse and click the Underline icon for the underlining effect. This happens even in web-based applications such as Gmail. Is there any way to rectify this? *(SACHIN BORKAR)*

I made a patch for unicode.mim in m17n-db to improve it a bit to be able to input all Unicode characters, also those above the BMP:

https://lists.nongnu.org/archive/html/m17n-list/2022-02/msg00001.html

I could not figure out yet how to change the Control+u shorcut, but when submitting my patch I asked whether it is possible to do that.

**Comment by mike-fabian** [comment]
Now I learned some possibilities how to control whether to use unicode.mim at all as a fallback in other input methods like mr-inscript2.mim.

Handa San explained to me that the fallback input methods are defined in

```
/usr/share/m17n/global.mim
```

which contains

```
(fallback-input-method
  (_"Fallback input methods.
Value must be comma separated fallback input method names.
When you type a key that is not handled by the currently activated intup method,
fallback input methods (in the order specified in this variable) try
to handle that key, and the first one that can handle the key is activated
temporarily.
For instance, as the default value of this variable is \"lsymbol, unicode\",
when you type \"/...\" while you are activating an input method
that doesn't handle that key sequence, \"lsymbol\" input method is activated
and \"…\" (U+2026: HORIZONTAL ELLIPSIS) is inserted.")
  "lsymbol, unicode"))
```

To change the list of fallback input methods, you can create the file

```
~/.m17n.d/config.mic
```

in your home directory (Create the `~/.m17n.d/` directory if it doesn’t exist).

and put

```
((input-method t nil global)
 (variable
  (fallback-input-method nil
   "unicode, lsymbol")))
```

into that file. If you use an empty string `""` instead of `"unicode, lsymbol"` it disables the fallback input methods completely and you cannot use this Unicode input anymore in other input methods like mr-inscript2.mim, you have to explicitly switch to unicode.mim then.

But maybe you want to keep using the Unicode input and just change the shortcut?

Then you can copy the system version of unicode.mim to the `~/.m17n.d/` directory:

```
cp /usr/share/m17n/unicode.mim   ~/.m17n.d/unicode.mim
```

and then change the shortcut for example like this:


```
(command
 (start (_"Start Unicode
Start typing hexadecimal numbers of Unicode character.")
	(G-C-z)))
```

As an example I replaced C-u here with G-C-z (AltGr+Control+z) which is unlikely to cause a conflict with anything.

You could also use G-u (AltGr+u). The right Alt key (AltGr) is used a lot in inscript input methods but AltGr+u is apparently not used in mr-inscript.mim and mr-inscript2.mim, so AltGr+u might be a suitable key binding for you to start Unicode input:


Checking that AltGr+u is not used in mr-inscript.mim and mr-inscript2.mim:

```
$ grep 'G-' /usr/share/m17n/mr-inscript*
/usr/share/m17n/mr-inscript.mim:  ((G-4) "₹")
/usr/share/m17n/mr-inscript2.mim:  ((G-1) "‍")
/usr/share/m17n/mr-inscript2.mim:  ((G-2) "‌")
/usr/share/m17n/mr-inscript2.mim:  ((G-4) "₹")
/usr/share/m17n/mr-inscript2.mim:  ((G-+) "ॠ")
/usr/share/m17n/mr-inscript2.mim:  ((G-=) "ॄ")
/usr/share/m17n/mr-inscript2.mim:  ((G-R) "ॡ")
/usr/share/m17n/mr-inscript2.mim:  ((G-r) "ॣ")
/usr/share/m17n/mr-inscript2.mim:  ((G-F) "ऌ")
/usr/share/m17n/mr-inscript2.mim:  ((G-f) "ॢ")
/usr/share/m17n/mr-inscript2.mim:  ((G-X) "ॐ")
/usr/share/m17n/mr-inscript2.mim:  ((G-,) "॰")
/usr/share/m17n/mr-inscript2.mim:  ((G->) "ऽ")
/usr/share/m17n/mr-inscript2.mim:  ((G-.) "॥")
```

No G-u (AltGr+u) there.

**Comment by mike-fabian** [comment]
Handa San also explained to me that currently m17n-lib cannot recognize the difference of C-u and C-U.

So using only Shift+Control+u but not Control+u to trigger Unicode input like ibus does  by default is not possible at the moment with m17n input methods. But AltGr+u `(G-u)` seems like a good alternative to me.

**Comment by mike-fabian** [comment]
I think I can close this issue because we have dealt with the reported problem.

Feel free to open new issues for specific remaining problems.

**Comment by sawaiborkar** [comment]
Yes, I agree. Thank you for taking out time to offer this great support to
me.
*(SACHIN BORKAR)*

**Comment by sawaiborkar** [comment]
Just a small help please.
I don't know the key (or key combination) which prints this character ('ऽ').
This is a very important character when it comes writing dialogues in
Marathi.

*(SACHIN BORKAR)*

**Comment by shantanuo** [comment]
".a" (fullstop followed by a) will print unicode character 093D ( ऽ ) in itrans or gamabhana.

**Comment by sawaiborkar** [comment]
Thank you.
Got that. Any idea about how to do this with inscript input method?
*(SACHIN BORKAR)*

**Comment by mike-fabian** [comment]
That character is available also in inscript2:

```
$ grep ऽ  /usr/share/m17n/mr-*mim
/usr/share/m17n/mr-gamabhana.mim:  (".a" "ऽ")
/usr/share/m17n/mr-inscript2.mim:  ((G->) "ऽ")
/usr/share/m17n/mr-itrans.mim:  (".a" "ऽ")
```

So with mr-inscript2.mim you can type it with AltGr+>

`G-` in the .mim files always means AltGr.

(AltGr is the right Alt key, you need to use a keyboard layout where the right Alt key does not just duplicate the left one but produces a ISO_Level3_Shift, the standard Indian English layout “English (India, with rupee)” is OK for this)

**Comment by sawaiborkar** [comment]
Hey Mike,
Just found out that Marathi keyboard layouts now also include the
Typewriter layout (including Remington one). I was very pleasantly
surprised to see that. Do you know who maintains the inscript layout
package? I want to thank them for including Typewriter layout in Marathi
inscript layouts for Ubuntu 22.04 LTS. Very Very useful addition to Marathi
keyboard layouts indeed!
Thanks.
*(SACHIN BORKAR)*

**Comment by mike-fabian** [comment]
> Hey Mike, Just found out that Marathi keyboard layouts now also include the Typewriter layout (including Remington one). I was very pleasantly surprised to see that. 

You can see the  `mr-.*.mim` files which are avaible upstream in m17n-db here:
https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM

Currently these are:

```
mr-gamabhana.mim
mr-inscript.mim
mr-inscript2.mim
mr-itrans.mim
mr-phonetic.mim
mr-remington.mim
mr-typewriter.mim
```

`mr-inscript2.mim` was added in the m17n-db-1.8.1 release, released 2023-05-03. The author of `mr-inscript2.mim` is Parag Nemade <pnemade@redhat.com>.

`mr-gamabhana.mim` was added in the m17n-db-1.8.2 release, released 2023-05-08. The author of `mr-gamabhana.mim` is @shantanuo . 

The other `mr-*.mim` input methods have been available for a very long time.

> Do you know who maintains the inscript layout package? I want to thank them for including Typewriter layout in Marathi inscript layouts for Ubuntu 22.04 LTS. Very Very useful addition to Marathi keyboard layouts indeed! Thanks. *(SACHIN BORKAR)*
