### ISSUE TITLE
[NOT A BUG] ibus not finding m17n engines

### ISSUE THREAD

**Issue by VITTHANI** [ibus/ibus-m17n#89]
I have installed the ibus-m17n using source code release, using `--prefix=$HOME/.local/ `. after using `ibus list-engines` (where ibus is available as an officially package on arch.) it is not listing m17n:xx:xxx like engines.

is there any path variables has to be declared!? 

whereas ibus-typing-booster package works fine (perhaps being an official arch package). can anyone describe what is the problem.

**Comment by mike-fabian** [comment]
Why `--prefix=$HOME/.local/`? I think that won't work.

On a “normal” installation, the ibus-m17n package contains this file `/usr/share/ibus/component/m17n.xml`

```
mfabian@hathi:~
$ rpm -qf /usr/share/ibus/component/m17n.xml 
ibus-m17n-1.4.33-1.fc41.x86_64
mfabian@hathi:~
$ cat /usr/share/ibus/component/m17n.xml 
<?xml version="1.0" encoding="utf-8"?>
<!-- filename: m17n.xml -->
<component>
        <name>org.freedesktop.IBus.M17N</name>
        <description>M17N Component</description>
        <exec>/usr/libexec/ibus-engine-m17n --ibus</exec>
        <version>1.4.33</version>
        <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
        <license>GPL</license>
        <homepage>http://code.google.com/p/ibus</homepage>
        <textdomain>ibus-m17n</textdomain>
        <observed-paths>
                <path>/usr/share/m17n/</path>
                <path>/usr/share/ibus-m17n/default.xml</path>
                <path>~/.m17n.d/</path>
        </observed-paths>
        <engines exec="/usr/libexec/ibus-engine-m17n --xml" />
</component>
mfabian@hathi:~
$ 
```

ibus uses this `m17n.xml` file to the the list of engines from `<engines exec="/usr/libexec/ibus-engine-m17n --xml" />` (running the command `/usr/libexec/ibus-engine-m17n --xml` lists all ibus-m17n engines.

If you installed in `~/.local/`, then you will probably find that `m17n.xml` file somewhere in `~/.local` but ibus won't search for it there.

**Comment by VITTHANI** [comment]
okay!  then after normal installation in `/usr/local/` and restarting the ibus service again, ibus is not generating `m17n.xml` on its own. does it mean one has to generate it manually using `ibus-engine-m17n --xml`? if so that concludes that ibus has no acknowledgement to `ibus-engine-m17` script or?

**Comment by VITTHANI** [comment]
I think there is path installation issue: default `configure` installs everything in `/usr/local/` but not `/usr/`. and installing in `/usr/` directory would cause replacement of base `ibus` package.

**Comment by mike-fabian** [comment]
> I think there is path installation issue: default `configure` installs everything in `/usr/local/` but not `/usr/`. and installing in `/usr/` directory would cause replacement of base `ibus` package.

If you install `ibus-m17n`, it won’t replace the base `ibus` package, it does not have any file conflicts with the base `ibus` package.

`/usr/share/ibus/component/m17n.xml` is owned bu the `ibus-m17n` package, not the `ibus` package. `ibus` just reads and uses it.

> It works only if installation is in same dir as `ibus`.

Yes!
